#!/usr/bin/ruby

# Read configs and set up server objects
require File.expand_path( File.join( File.dirname(__FILE__), "server.rb") )   # in same folder as current file
server_config = ServerConfig.new 'master.yml'
worker = Server.new server_config, :worker

# Initiate the update on the worker
def initiate_update worker
  puts "--------"
  puts "Starting update at #{Time.now}"
  worker.up
  puts "Initiating remote update at #{Time.now}."
  if worker.initiate "#{server_config.update} >> #{server_config.log}"
    puts 'OK'
    #we're done, remote script will handle shutdown after it finishes
  else
    raise 'Failed to initiate remote update!'
  end
rescue Exception => e
  puts e
  worker.shutdown
ensure
  puts "\n\n"
end

# Read command line options and take action
if ARGV[0]=='update'
  initiate_update
elsif ARGV[0]=='up'
  worker.up
elsif ARGV[0]=='down'
  worker.down
elsif ARGV[0]=='status'
  puts worker.status
elsif ARGV[0]=='test'
  puts "Test at #{Time.now}."
end