#!/usr/bin/ruby

require 'fileutils'
require 'rubygems'
require 'savon'

config = YAML.load_file('process.yml')

USERNAME = config['username']
PASSWORD = config['password']
SERVER_ID = config['server_id']

ROOT = File.expand_path '~'
BIN_PATH  = ROOT+'/Project-OSRM/build'
DATA_FOLDER = ROOT+'/var'
REPLICATION_FOLDER = 'replicate'
PROFILES = ['bicycle']
PROFILES_FOLDER = ROOT+'/Project-OSRM/profiles'
MAP_NAME = 'map'
POLYGON = ROOT+"/var/#{MAP_NAME}.poly"
PACKAGE_NAME = 'data'
OSM_FILE = "#{MAP_NAME}.osm.pbf"
NEWFILE = "#{MAP_NAME}_new.osm.pbf"
USER = 'root'
SERVER = 'routes.ibikecph.dk'
SERVER_ROOT = '/home/osm'
RENDER_OPTIONS = 'z=9-17 bbox=7.64,54.33,13.37,57.98 map=solar'
SERVER_BIN_PATH = SERVER_ROOT + '/Project-OSRM'

Savon.configure do |config|
  config.log = false
end

HTTPI.log = false

def time str, &block
  start = Time.now
  puts '---------'
  puts "#{str}: Starting at #{start}"
  yield block
  finish = Time.now
  seconds = (Time.now - start).to_i
  formatted = format_time seconds
  puts "#{str}: Completed in #{seconds}s / #{formatted}, at #{finish}."
end

def run_cmd cmd
  puts cmd
  raise "Failed to run command: #{cmd}" unless system cmd
end

def replicate
  Dir.chdir DATA_FOLDER do
    run_cmd "osmosis --read-replication-interval workingDirectory=#{REPLICATION_FOLDER} --simplify-change --read-pbf file=#{OSM_FILE} --apply-change --bounding-polygon file=#{POLYGON} --write-pbf file=#{NEWFILE} omitmetadata=true"
    FileUtils.mv NEWFILE, OSM_FILE
  end
end

def process
  run_cmd "rm -rf #{DATA_FOLDER}/#{PACKAGE_NAME}"
  run_cmd "mkdir -p #{DATA_FOLDER}/#{PACKAGE_NAME}"
  Dir.chdir "#{DATA_FOLDER}" do
    for profile in PROFILES do
      puts '----'
      puts "Processing profile: #{profile}"
      profile_path = "#{PROFILES_FOLDER}/#{profile}.lua"
      run_cmd "rm -rf #{MAP_NAME}.osrm*"
      puts
      run_cmd "#{BIN_PATH}/osrm-extract #{OSM_FILE} #{profile_path}"
      puts
      run_cmd "#{BIN_PATH}/osrm-prepare #{MAP_NAME}.osrm #{MAP_NAME}.osrm.restrictions #{profile_path}"
      puts
      run_cmd "mkdir -p #{PACKAGE_NAME}/#{profile}; mv #{MAP_NAME}.osrm* #{PACKAGE_NAME}/#{profile}/"
      puts
    end
  end
end

def copy_binaries
  run_cmd "cp #{BIN_PATH}/osrm-* #{DATA_FOLDER}/#{PACKAGE_NAME}/"
end

def rsync_osrm_data
  run_cmd "rsync #{DATA_FOLDER}/#{PACKAGE_NAME} #{USER}@#{SERVER}:/tmp/#{PACKAGE_NAME}/"
end

def postgres
  run_cmd "osm2pgsql -d osm -U osm -c -C8000 --number-processes=4 #{DATA_FOLDER}/#{OSM_FILE}"
end

def remove_tiles
  run_cmd "rm -rf /tiles/plain/*"
end

def render_tiles
  run_cmd "tirex-batch #{RENDER_OPTIONS}"
  raw = ''
  (20*60).times do |i|
    sleep 60
    raw = `tirex-status --raw`
    size = /"size" : (\d+)/.match(raw)[1].to_i
    if i%30 == 0
      puts "#{size} tiles left to render, at #{Time.now}"
    end
    return if size==0
  end
  raise "Rendering timed out! Last tirex-status raw: #{raw}"
end

def convert_tiles
  run_cmd "#{ROOT}/meta2tile /tiles/meta /tiles/plain"
end

def sync_tiles
  run_cmd "rsync -r --ignore-times /tiles/plain/ tiles.ibikecph.dk:/tiles/plain/"
end

def deploy
  log_msg = "OSRM update deployed at #{Time.now}"
  cmd = <<-EOF
    rm -rf #{SERVER_ROOT}/#{PACKAGE_NAME}_old;
    stop osrm;
    mv #{SERVER_ROOT}/#{PACKAGE_NAME} #{SERVER_ROOT}/#{PACKAGE_NAME}_old;
    mv /tmp/#{MAP_NAME} #{SERVER_ROOT}/#{PACKAGE_NAME};
    start osrm;
    echo '#{log_msg}' >> #{SERVER_ROOT}/log/deploy.log;
  EOF
  run_cmd %{ssh #{USER}@#{SERVER} "#{cmd}" }
end

def shutdown
  puts 'Shutting down'
  client = Savon::Client.new do
    wsdl.document = "https://api.cloud.dk/?wsdl"
    http.auth.basic USERNAME, PASSWORD
    http.auth.ssl.verify_mode = :none
  end
  client.request :stop_server, :body => { 'server_id' => SERVER_ID, 'stop_method' => 1 }
end

def format_time total_seconds
  seconds = total_seconds % 60
  minutes = (total_seconds / 60) % 60
  hours = total_seconds / (60 * 60)
  format("%02d:%02d:%02d", hours, minutes, seconds)
end

def update
  puts '---------------------------------------'
  time("Updating") do
    begin
      run_cmd "df -h"
      run_cmd "free -m"
      if ARGV.empty? || ARGV.include?('osm')
        time("Updating OSM data") { replicate }
      end
      if ARGV.empty? || ARGV.include?('osrm')
        time("Preprocess OSRM data") { process }
        time("Copy binaries") { copy_binaries }
        time("Sync data to route server") { rsync_osrm_data }
        time("Swap folders and restart OSRM") { deploy }
      end
      if ARGV.empty? || ARGV.include?('tiles')
        time("Import to Postgres") { postgres }
        time("Render meta-tiles") { render_tiles }
        time("Remove old tiles") { remove_tiles }
        time("Convert meta-tiles") { convert_tiles }
        time("Sync tiles to tiles server") { sync_tiles }
      end
    rescue Exception => e
      puts "*** An error occurred:"
      puts e
    ensure
      if ARGV.empty? || ARGV.include?('shutdown')
        time("Shutdown") { shutdown }
      end
    end
  end
end

update